name: tokenizer

services:
  smart-contract-service:
    container_name: smart-contract-service
    restart: on-failure
    volumes:
      - ./deployment/test:/usr/src/app/test
      - ./code:/usr/src/app/code
      - ./deployment/contractData/:/usr/src/app/contractData
    environment:
      SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY:?}
      FUJI_CHAIN_ID: ${FUJI_CHAIN_ID:?}
      FUJI_RPC_URL: ${FUJI_RPC_URL:?}
    build:
        context: ./
        dockerfile: ./deployment/Dockerfile.dev
    expose:
      - 3000
    ports:
      - 8545:8545
    networks:
      - router

networks:
  router:
    driver: bridge