FROM node:24-alpine

WORKDIR /usr/src/app

RUN apk update --no-cache && \ 
    apk add pnpm

COPY ../code /usr/src/app/code
COPY ./ /usr/src/app/

RUN pnpm i --prod

RUN chmod +x deploy.sh 

ENTRYPOINT [ "./deploy.sh" ]